name: simplelinewrapper
description: "Simple Line Wrapper allows you to wrap lines of text efficiently by creating predefined wrappers"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  url_launcher: ^6.2.6
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.8.0
  shared_preferences: ^2.3.3
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
  - assets/
